import java.util.HashMap;
import java.util.Map;

public class day2_part1 {
    public static void main(String[] args) {

        String input =
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C X\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A X\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "B X\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B X\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "A Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B X\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "A Z\n" +
                "B X\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "B Z\n" +
                "C Z\n" +
                "A X\n" +
                "A X\n" +
                "B Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A X\n" +
                "A X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Z\n" +
                "C X\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "B X\n" +
                "A Y\n" +
                "C Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Y\n" +
                "B Z\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "B X\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Z\n" +
                "C X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "C X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A X\n" +
                "B Y\n" +
                "B Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A X\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A X\n" +
                "A X\n" +
                "C Z\n" +
                "A X\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A X\n" +
                "C X\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C X\n" +
                "C X\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B X\n" +
                "C X\n" +
                "B X\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "B X\n" +
                "C X\n" +
                "A Z\n" +
                "B X\n" +
                "B Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Z\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C X\n" +
                "A Z\n" +
                "B Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Y\n" +
                "B Y\n" +
                "B Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "C X\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Z\n" +
                "C X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A X\n" +
                "B Y\n" +
                "B Y\n" +
                "B Y\n" +
                "C Z\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C X\n" +
                "C Y\n" +
                "B X\n" +
                "B Y\n" +
                "B X\n" +
                "A Z\n" +
                "C X\n" +
                "C Z\n" +
                "B Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "B X\n" +
                "A Z\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "B Z\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B X\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "A Z\n" +
                "A X\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "A Y\n" +
                "C Y\n" +
                "B Z\n" +
                "A Y\n" +
                "A X\n" +
                "C Y\n" +
                "C Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "A Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Y\n" +
                "B Y\n" +
                "A Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "C Y\n" +
                "C Y\n" +
                "C Z\n" +
                "B Y\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Y\n" +
                "A Z\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Y\n" +
                "B Z\n" +
                "B Y\n" +
                "C Z\n" +
                "C Y\n" +
                "A Y\n" +
                "B X\n" +
                "C Z\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "A Z\n" +
                "B Y\n" +
                "B Y\n" +
                "C Y\n" +
                "A Z\n" +
                "A Z\n" +
                "C Z\n" +
                "A Y\n" +
                "B Y\n" +
                "A Y\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "A Z\n" +
                "C Y\n" +
                "A Z\n" +
                "B Z\n" +
                "B Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "B Y\n" +
                "C Y\n" +
                "B Z\n" +
                "C Y\n" +
                "C Z\n" +
                "A X\n" +
                "C Y\n" +
                "B Z\n" +
                "B Z\n" +
                "A X\n" +
                "A X\n" +
                "C Y\n" +
                "C Y\n" +
                "C Y\n" +
                "A Y\n" +
                "A Z\n" +
                "A X\n" +
                "C Y\n";

        String input2 = "A Y\n" +
                "B X\n" +
                "C Z";

        String[] inputSplitted = input.split("\n");

        Map<String, Integer> data = new HashMap<>();
        data.put("A", 1); // Rock
        data.put("B", 2); // Paper
        data.put("C", 3); // Cissor

        data.put("X", 1); // Rock
        data.put("Y", 2); // Paper
        data.put("Z", 3); // Cissor


        int totalScore = 0;
        for (String s : inputSplitted) {
            String[] split = s.split(" ");
            String elf = split[0];
            String player = split[1];

            Map.Entry<String, Integer> elfResult = data.entrySet().stream().filter(characterIntegerEntry -> characterIntegerEntry.getKey().equals(elf)).findFirst().get();
            Map.Entry<String, Integer> playerResult = data.entrySet().stream().filter(characterIntegerEntry -> characterIntegerEntry.getKey().equals(player)).findFirst().get();

            totalScore += playerResult.getValue();

            // Find out who won
            if (elfResult.getValue() == 1 && playerResult.getValue() == 3) {
                // elf win
                totalScore += 0;
            } else if (elfResult.getValue() == 1 && playerResult.getValue() == 1) {
                // draw
                totalScore += 3;
            } else if (elfResult.getValue() == 1 && playerResult.getValue() == 2) {
                // elf loose
                totalScore += 6;
            } else if (elfResult.getValue() == 2 && playerResult.getValue() == 3) {
                // elf loose
                totalScore += 6;
            } else if (elfResult.getValue() == 2 && playerResult.getValue() == 2) {
                // draw
                totalScore += 3;
            } else if (elfResult.getValue() == 2 && playerResult.getValue() == 1) {
                // elf win
                totalScore += 0;
            } else if (elfResult.getValue() == 3 && playerResult.getValue() == 1) {
                // elf loose
                totalScore += 6;
            } else if (elfResult.getValue() == 3 && playerResult.getValue() == 3) {
                // draw
                totalScore += 3;
            } else if (elfResult.getValue() == 3 && playerResult.getValue() == 2) {
                // elf win
                totalScore += 0;
            }
        }
        System.out.println(String.format("Total score: %d", totalScore));
    }
}
